### ISSUE TITLE
Cannot include images

### ISSUE THREAD

**Issue by ohenrik** [trade-informatics/caracal#30]
Whenever i try to include an image in the template the server crashes due to ThreadError.

I'm trying to call this in `show.docx.caracal`:
`docx.img project.thumbnail_url(:cv), width: 300, height: 300, align: :left`

Where `project.thumbnail_url(:cv)` is `http://localhost:3000/assets/cv_default-34ff320be9c011ccaef4b564c308a0518b07329df2f62055e00738f4593577fd.png` (the file is delivered correctly)

Any idea why this might be happening?

Here is the error if i let the server time out:
```
Completed 500 Internal Server Error in 120097ms (ActiveRecord: 3.9ms)

ActionView::Template::Error (Net::ReadTimeout):
    1: docx.style do
    2:   id 'Normal'
    3:   name 'Normal'
    4:   font   'Calibri'
  app/views/cv_exports/show.docx.caracal:1:in `block in singleton class'
  app/views/cv_exports/show.docx.caracal:-2:in `instance_eval'
  app/views/cv_exports/show.docx.caracal:-2:in `singleton class'
  app/views/cv_exports/show.docx.caracal:-4:in `__tilt_70195351606480'
  app/views/cv_exports/show.docx.caracal:1:in `_app_views_cv_exports_show_docx_caracal___2175006984916252707_70195432268340'


  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.3ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.6ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (73.9ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.3ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (61.0ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.5ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (129.1ms)


Started GET "/assets/cv_default-34ff320be9c011ccaef4b564c308a0518b07329df2f62055e00738f4593577fd.png" for ::1 at 2016-02-18 15:20:32 +0100


Started GET "/assets/cv_default-34ff320be9c011ccaef4b564c308a0518b07329df2f62055e00738f4593577fd.png" for ::1 at 2016-02-18 15:20:32 +0100
[2016-02-18 15:20:32] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `eof?'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `run'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Here is my entire stack trace (after i manually kill the server):
```
  Rendered cv_exports/show.docx.caracal (2272.8ms)
Completed 401 Unauthorized in 2340ms (ActiveRecord: 13.2ms)
[2016-02-18 15:12:54] ERROR ThreadError: Attempt to unlock a mutex which is locked by another thread
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:22:in `unlock'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:22:in `ensure in call'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:23:in `call'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
/Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:48:in `shutdown': undefined method `shutdown' for nil:NilClass (NoMethodError)
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:280:in `block in start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:206:in `call'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:206:in `join'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:206:in `block (2 levels) in start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:206:in `each'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:206:in `block in start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:32:in `start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:162:in `start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/server.rb:80:in `start'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/ohenrik/Sites/menon_projects/bin/rails:9:in `require'
	from /Users/ohenrik/Sites/menon_projects/bin/rails:9:in `<top (required)>'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/client/rails.rb:28:in `load'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/client/rails.rb:28:in `call'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/client/command.rb:7:in `call'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/client.rb:28:in `run'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/bin/spring:49:in `<top (required)>'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/binstub.rb:11:in `load'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.5.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ohenrik/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ohenrik/Sites/menon_projects/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
zlib(finalizer): the stream was freed prematurely.
```

**Comment by jdugan** [comment]
I believe this is due to webrick running under a single process.  Because the file you're loading is also being served from your webrick server, my guess is you're getting a timeout on the image request (because webrick is locked trying to render the caracal page).

I suspect if you run your local environment with a multi-process web server like unicorn or puma, everything will work normally.

**Comment by ohenrik** [comment]
Yeah that did the trick. Used puma with 2 workers. However, why does this not happen when I'm rendering other templates? Is there a solution to this problem other than using multiple workers?

**Comment by jdugan** [comment]
Cool.

No, there really isn't.  So, when Rails renders an image in an HTML page, all it's doing is formatting an `img` tag and adding a link to the image resource--like your other templates, all the rendering is internal to Rails.  It doesn't actually care what the image is.  The link is just a text string. The image data itself isn't read until your browser uses the link to fetch the url after the page has been loaded.  

But a Word document actually _embeds_ the image data in the file that constitutes the HTTP response.  To do so, Caracal has to use `open-uri` to read the image data associated with your url when it processes the block.  It then saves that image data to a tmp file that gets zipped up into the final `.docx` deliverable.

So, when you use an external url, this poses no problem to webrick, since the `open-uri` call hits another server, which presumably is not busy.  But, when you call a url from your own project, the `open-uri` call cannot be answered because webrick's one process is already blocking...because it's waiting for that `open-uri` call to finish.  It sort of a snake eating its own tail.

In production/staging environments, this tends not to be an issue since you'd always be using a multi-process server there.

**Comment by ohenrik** [comment]
That makes sense! Didn't think about the fact that img tags only need the link, not the actual image. :)
